version: '3.9'

services:
  urlshorten_cache:
    image: redis:7.2.0-alpine
    ports:
      - "6379:6379"
    networks:
      - urlshorten_network

  urlshorten_db:
    image: postgres:14
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - urlshorten_network

  urlshorten_pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "dev@dev.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "8080:80"
    depends_on:
      - urlshorten_db
    volumes:
      - ./volumes/pgadmin:/var/lib/pgadmin
    networks:
      - urlshorten_network

networks:
  urlshorten_network:
    driver: bridge