"""empty message

Revision ID: 0b5149d679df
Revises: 
Create Date: 2023-08-21 12:13:09.930883

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0b5149d679df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shortened_urls',
    sa.Column('code', sa.VARCHAR(), nullable=False),
    sa.Column('destination_url', sa.String(), nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shortened_urls_code'), 'shortened_urls', ['code'], unique=True)
    op.create_index(op.f('ix_shortened_urls_id'), 'shortened_urls', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shortened_urls_id'), table_name='shortened_urls')
    op.drop_index(op.f('ix_shortened_urls_code'), table_name='shortened_urls')
    op.drop_table('shortened_urls')
    # ### end Alembic commands ###
